# Generated by Django 4.1.1 on 2022-09-18 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Biznes nomi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Start up',
                'verbose_name_plural': 'Start up',
                'ordering': ('-date_created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Revenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120, verbose_name='Hisobot nomi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='startups.startups', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Hisobot',
                'verbose_name_plural': 'Hisobotlar',
                'ordering': ('-date_created',),
                'abstract': False,
                'unique_together': {('name', 'startup')},
            },
        ),
        migrations.CreateModel(
            name='RevenueFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Hisobot nomi')),
                ('value', models.IntegerField(default=0, verbose_name='Hisobot qiymati')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='startups.revenues', verbose_name='Hisobot')),
            ],
            options={
                'verbose_name': 'Hisobot sohasi',
                'verbose_name_plural': 'Hisobotlar sohasi',
                'ordering': ('-date_created',),
                'abstract': False,
                'unique_together': {('name', 'revenue')},
            },
        ),
    ]
