# Generated by Django 4.1.1 on 2022-09-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenuefields',
            options={'ordering': ('date_created',), 'verbose_name': 'Hisobot sohasi', 'verbose_name_plural': 'Hisobotlar sohasi'},
        ),
        migrations.AlterModelOptions(
            name='revenues',
            options={'ordering': ('date_created',), 'verbose_name': 'Hisobot', 'verbose_name_plural': 'Hisobotlar'},
        ),
        migrations.AlterModelOptions(
            name='startups',
            options={'ordering': ('date_created',), 'verbose_name': 'Start up', 'verbose_name_plural': 'Start up'},
        ),
        migrations.AddField(
            model_name='revenuefields',
            name='is_plus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='revenuefields',
            name='percentage',
            field=models.FloatField(default=0.0, verbose_name="O'zgarish miqdori % da"),
        ),
    ]
